goimports の再修正

diff --git a/.github/workflows/makefile.yml b/.github/workflows/makefile.yml
--- a/.github/workflows/makefile.yml
+++ b/.github/workflows/makefile.yml
@@ -23,10 +23,10 @@ jobs:
         run: |
           go install golang.org/x/tools/cmd/goimports@latest
           DIFF=$(goimports -l .)
-#          if [ ! -z "$DIFF"] then
-#            echo "failed to check goimports. diff: [$DIFF]"
-#            exit 1
-#          fi
+          if [ ! -z "$DIFF"]; then
+            echo "failed to check goimports. diff: [$DIFF]"
+            exit 1
+          fi
 
   build:
     needs: [lint]
